/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import java.awt.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Organization;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.event.KeyEvent;

/**
 * @author braya
 */
public class ManageRestaurantsJPanel extends javax.swing.JPanel {

  /**
   * Creates new form ManageRestaurantsJPanel
   */

    JPanel userProcessContainer;
    EcoSystem system;

//    Organization organization;

    public ManageRestaurantsJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = ecosystem;
        populateRestaurantListTable();
     }

    public void populateRestaurantListTable() {
        DefaultTableModel model = (DefaultTableModel) tblRestaurantsList.getModel();
        model.setRowCount(0);

        for (Restaurant restaurant : system.getRestaurantDirectory().getRestaurantList()) {
            Object row[] = new Object[5];
            row[0] = restaurant;
            row[1] = restaurant.getAddress();
            row[2] = restaurant.getCuisineType();
            row[3] = restaurant.hasManager()? restaurant.getManager().getName():"";
            row[4] = restaurant.hasManager()?restaurant.getManager().getUseraccount().getUsername():"";
            
            //row[4] = airliner.getFlightDir().getFlightList().size();
            model.addRow(row);
        }
        
    }

            

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurantsList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnnewrestaurant = new javax.swing.JButton();
        btnupdaterestaurant = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSearchRestaurant = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btndeleterestaurant = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();

        tblRestaurantsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant Name", "Address", "Cuisine Type", "Manager Name", "Manager User Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRestaurantsList);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Restaurants List");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Restaurants");

        btnnewrestaurant.setText("New Restaurant>>");
        btnnewrestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewrestaurantActionPerformed(evt);
            }
        });

        btnupdaterestaurant.setText("Update Restaurant");
        btnupdaterestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdaterestaurantActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Restaurant Name");

        txtSearchRestaurant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchRestaurantKeyPressed(evt);
            }
        });

        btnSearch.setText("Search Restaurant");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btndeleterestaurant.setText("Delete restaurant");
        btndeleterestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleterestaurantActionPerformed(evt);
            }
        });

        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btndeleterestaurant)
                                    .addGap(53, 53, 53)
                                    .addComponent(btnnewrestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnupdaterestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(147, 147, 147))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btndeleterestaurant, btnnewrestaurant, btnupdaterestaurant});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnback))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndeleterestaurant)
                    .addComponent(btnnewrestaurant)
                    .addComponent(btnrefresh)
                    .addComponent(btnupdaterestaurant))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(231, 231, 231))
        );
    }// </editor-fold>//GEN-END:initComponents

  private void btnnewrestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewrestaurantActionPerformed
    // TODO add your handling code here:
    CreateNewRestaurantJPanel panel = new CreateNewRestaurantJPanel(userProcessContainer, system);
    userProcessContainer.add("CreateNewRestaurantJPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);

  }//GEN-LAST:event_btnnewrestaurantActionPerformed

  private void btnupdaterestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdaterestaurantActionPerformed
    int selectedRow = tblRestaurantsList.getSelectedRow();
    if (selectedRow < 0) {
      JOptionPane.showMessageDialog(null, "Please select a row");
      return;
    }

    Restaurant rt = (Restaurant) tblRestaurantsList.getValueAt(selectedRow, 0);
    
    UpdateRestaurantJPanel panel;
    if (rt.hasManager()){
        UserAccount ua = rt.getManager().getUseraccount();
        panel = new UpdateRestaurantJPanel(userProcessContainer, rt, ua, system);
    }else{
        panel = new UpdateRestaurantJPanel(userProcessContainer, rt, system);
    }
    
    
    userProcessContainer.add("UpdateRestaurantJPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);

  }//GEN-LAST:event_btnupdaterestaurantActionPerformed

  private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
    // TODO add your handling code here:

    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);

    Component[] comps = this.userProcessContainer.getComponents();
    for (Component comp : comps) {
      if (comp instanceof SystemAdminWorkAreaJPanel) {
        SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel = (SystemAdminWorkAreaJPanel) comp;
        systemAdminWorkAreaJPanel.populateTree();
      }
    }
//        layout.previous(userProcessContainer);
  }//GEN-LAST:event_btnbackActionPerformed

  private void btndeleterestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleterestaurantActionPerformed
    // TODO add your handling code here:
    int selectedRow = tblRestaurantsList.getSelectedRow();
    if (selectedRow < 0) {
      JOptionPane.showMessageDialog(null, "Please select a row");
      return;
    }

    Restaurant rt = (Restaurant) tblRestaurantsList.getValueAt(selectedRow, 0);
    system.getRestaurantDirectory().deleteRestaurant(rt);
    populateRestaurantListTable();
//      Enterprise e = (Enterprise) tblRestaurantsList.getValueAt(selectedRow, 2);
//      system.getEnterpriseDirectory().deleteEnterprise(e);
//      JOptionPane.showMessageDialog(null, "Restaurant deleted successfully");
//      populateRestaurantListTable();
    

  }//GEN-LAST:event_btndeleterestaurantActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        String restaurantName = txtSearchRestaurant.getText();
        
        if (restaurantName.equals("")){
            JOptionPane.showMessageDialog(this, "!Error!\nEnter a Resturant name to Search");
            return;
        }
        
        if (system.getRestaurantDirectory().checkIfRestaurantnameIsUnique(restaurantName)){
            JOptionPane.showMessageDialog(this, "!Error!\nResturant Doesn't exist");
            return;
        }
        JOptionPane.showMessageDialog(this, "Resturant Found");
        int index = system.getRestaurantDirectory().checkIfRestaurantExists(restaurantName);
        Restaurant rt = system.getRestaurantDirectory().getRestaurantList().get(index);
        DefaultTableModel model = (DefaultTableModel) tblRestaurantsList.getModel();
        model.setRowCount(0);
        
        Object row[] = new Object[5];
        row[0] = rt.getRestaurantName();
        row[1] = rt.getAddress();
        row[2] = rt.getCuisineType();
        row[3] = rt.hasManager()? rt.getManager().getName():"";
        row[4] = rt.hasManager()?rt.getManager().getUseraccount().getUsername():"";

        model.addRow(row);
        txtSearchRestaurant.setText("");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        populateRestaurantListTable();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void txtSearchRestaurantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchRestaurantKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSearch.doClick();
        }
    }//GEN-LAST:event_txtSearchRestaurantKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndeleterestaurant;
    private javax.swing.JButton btnnewrestaurant;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnupdaterestaurant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRestaurantsList;
    private javax.swing.JTextField txtSearchRestaurant;
    // End of variables declaration//GEN-END:variables
}
