/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import java.awt.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import Business.EcoSystem;
import Business.Organization;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;

/**
 * @author braya
 */
public class ManageRestaurantsJPanel extends javax.swing.JPanel {

  /**
   * Creates new form ManageRestaurantsJPanel
   */

    JPanel userProcessContainer;
    EcoSystem ecosystem;

//    Organization organization;

    public ManageRestaurantsJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        populateRestaurantListTable();
     }

    public void populateRestaurantListTable() {
        DefaultTableModel model = (DefaultTableModel) tblRestaurantsList.getModel();
        model.setRowCount(0);

        for (Restaurant restaurant : ecosystem.getRestaurantDirectory().getRestaurantList()) {
            Object row[] = new Object[3];
            row[0] = restaurant.getRestaurantName();
            row[1] = restaurant.getAddress();
            row[2] = restaurant.getCuisineType();
            //row[4] = airliner.getFlightDir().getFlightList().size();
            model.addRow(row);
        }
        
        DefaultTableModel model2 = (DefaultTableModel) tblSearchRestaurant.getModel();
        model2.setRowCount(0);
    }
    
    public void populateSearchTable() {
        
        DefaultTableModel model2 = (DefaultTableModel) tblSearchRestaurant.getModel();
        model2.setRowCount(0);
        
        for (Restaurant restaurant : ecosystem.getRestaurantDirectory().getRestaurantList()) {
            if(restaurant.getRestaurantName().equalsIgnoreCase(txtSearchRestaurant.getText())){
                Object row1[] = new Object[3];
                row1[0] = restaurant.getRestaurantName();
                row1[1] = restaurant.getManager().getName();
                row1[2] = restaurant.getManager().getUseraccount().getUsername();

                model2.addRow(row1);
            }
        }
    }
            

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurantsList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnnewrestaurant = new javax.swing.JButton();
        btnupdaterestaurant = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSearchRestaurant = new javax.swing.JTable();
        btnupdatemanagers = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSearchRestaurant = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btndeletemanager = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btndeleterestaurant = new javax.swing.JButton();

        tblRestaurantsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant Name", "Address", "Cuisine Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRestaurantsList);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Restaurants List");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Restaurants");

        btnnewrestaurant.setText("New Restaurant>>");
        btnnewrestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewrestaurantActionPerformed(evt);
            }
        });

        btnupdaterestaurant.setText("Update Restaurant");
        btnupdaterestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdaterestaurantActionPerformed(evt);
            }
        });

        tblSearchRestaurant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant Name", "Manager Name", "Manager User Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSearchRestaurant);

        btnupdatemanagers.setText("Update Managers");
        btnupdatemanagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatemanagersActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Restaurant Name");

        btnSearch.setText("Search Restaurant");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btndeletemanager.setText("Delete Manger");
        btndeletemanager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletemanagerActionPerformed(evt);
            }
        });

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btndeleterestaurant.setText("Delete restaurant");
        btndeleterestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleterestaurantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnupdatemanagers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btndeletemanager, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearchRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btndeleterestaurant)
                                .addGap(89, 89, 89)
                                .addComponent(btnnewrestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnupdaterestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnnewrestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnupdaterestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btndeleterestaurant))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdatemanagers, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndeletemanager, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

  private void btnnewrestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewrestaurantActionPerformed
    // TODO add your handling code here:
    CreateNewRestaurantJPanel panel = new CreateNewRestaurantJPanel(userProcessContainer, ecosystem);
    userProcessContainer.add("CreateNewRestaurantJPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);

  }//GEN-LAST:event_btnnewrestaurantActionPerformed

  private void btnupdaterestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdaterestaurantActionPerformed
    // TODO add your handling code here:
    UpdateRestaurantJPanel panel = new UpdateRestaurantJPanel(userProcessContainer, ecosystem);
    userProcessContainer.add("UpdateRestaurantJPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);

  }//GEN-LAST:event_btnupdaterestaurantActionPerformed

  private void btnupdatemanagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatemanagersActionPerformed
    // TODO add your handling code here:
    int selectedRow = tblSearchRestaurant.getSelectedRow();
    if (selectedRow < 0) {
      JOptionPane.showMessageDialog(null, "Please select a row");
      return;
    } else {
//      UserAccount ua = (UserAccount) tblSearchRestaurant.getValueAt(selectedRow, 2);
//      UpdateUserJPanel panel = new UpdateUserJPanel(userProcessContainer, ua, "RestaurantAdmin");
//      userProcessContainer.add("UpdateManagerJPanel", panel);
//      CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//      layout.next(userProcessContainer);
    }
  }//GEN-LAST:event_btnupdatemanagersActionPerformed

  private void btndeletemanagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletemanagerActionPerformed
    // TODO add your handling code here:
    populateRestaurantListTable();
    tblRestaurantsList.revalidate();
    tblRestaurantsList.repaint();
    tblSearchRestaurant.revalidate();
    tblSearchRestaurant.repaint();
  }//GEN-LAST:event_btndeletemanagerActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:

    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);

    Component[] comps = this.userProcessContainer.getComponents();
    for (Component comp : comps) {
      if (comp instanceof SystemAdminWorkAreaJPanel) {
        SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel = (SystemAdminWorkAreaJPanel) comp;
        systemAdminWorkAreaJPanel.populateTree();
      }
    }
//        layout.previous(userProcessContainer);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void btndeleterestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleterestaurantActionPerformed
    // TODO add your handling code here:
    int selectedRow = tblRestaurantsList.getSelectedRow();
    if (selectedRow < 0) {
      JOptionPane.showMessageDialog(null, "Please select a row");
      return;
    } else {
//      Enterprise e = (Enterprise) tblRestaurantsList.getValueAt(selectedRow, 2);
//      ecosystem.getEnterpriseDirectory().deleteEnterprise(e);
//      JOptionPane.showMessageDialog(null, "Restaurant deleted successfully");
//      populateRestaurantListTable();
    }

  }//GEN-LAST:event_btndeleterestaurantActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        //    Enterprise result = ecosystem.getEnterpriseDirectory().searchEnterprise(txtSearchRestaurant.getText());
////    RestaurantDirectory temp = ecosystem.getRestaurantDirectory();
//    Organization organization1 = result.getRestaurantDirectory().searchOrganization("RestaurantAdmin");
//    if (result == null) {
//      JOptionPane.showMessageDialog(null, "Restaurant entered does not exist", "Information", JOptionPane.INFORMATION_MESSAGE);
//      DefaultTableModel model = (DefaultTableModel) tblSearchRestaurant.getModel();
//      model.setRowCount(0);
//    } else {
//      DefaultTableModel model = (DefaultTableModel) tblSearchRestaurant.getModel();
//      model.setRowCount(0);
//      for (UserAccount userAccount : organization1.getUserAccountDirectory().getUserAccountList()) {
//        Object row[] = new Object[3];
//        row[0] = result.getName();
//        row[1] = userAccount.getEmployee().getName();
//
//        row[2] = userAccount;
//
//        model.addRow(row);
//      }
//    }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btndeletemanager;
    private javax.swing.JButton btndeleterestaurant;
    private javax.swing.JButton btnnewrestaurant;
    private javax.swing.JButton btnupdatemanagers;
    private javax.swing.JButton btnupdaterestaurant;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRestaurantsList;
    private javax.swing.JTable tblSearchRestaurant;
    private javax.swing.JTextField txtSearchRestaurant;
    // End of variables declaration//GEN-END:variables
}
