/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Area.AreaName;
import Area.AreaNetwork;
import Business.EcoSystem;
import Business.SysAdmin.SysAdmin;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gunav
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userLogged;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userLogged) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.userLogged=userLogged;
        populateAreas();
        populateSysAdmins();
    }
    
    private void populateAreas() {
        
        List<AreaNetwork> areaNetworks = ecosystem.getAreaNetworks();
        areajComboBox.removeAllItems();
        for(AreaNetwork areaNetwork:areaNetworks){
            areajComboBox.addItem(areaNetwork.getAreaName().name());
        }
        
        addAreajComboBox.removeAllItems();
        for(String areaName:AreaName.getAreasList()){
            addAreajComboBox.addItem(areaName);
        }
        addAreajComboBox.setSelectedIndex(addAreajComboBox.getItemCount()-1);
    }
    
    public void populateSysAdmins() {
        
        DefaultTableModel sysAdminsModel = (DefaultTableModel) sysAdminsjTable.getModel();
        sysAdminsModel.setRowCount(0);
        
        int sysAdminsCount=0;
        for(SysAdmin sysAdmin:ecosystem.getSysAdminDirectory().getSysAdmins()) {
            sysAdminsCount++;
            Object[] row = new Object[6];
            row[0]=sysAdminsCount;
            row[1]=sysAdmin;
            row[2]=sysAdmin.getUserAccount().getUserName();
            row[3]=sysAdmin.getUserAccount().getPassword();
            row[4]=sysAdmin.getUserAccount().getEmail();
            row[5]=sysAdmin.getUserAccount().getPhoneNo();
            
            sysAdminsModel.addRow(row);
        }
        countTotaljLabel.setText(String.valueOf(ecosystem.getSysAdminDirectory().getSysAdmins().size()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        areajComboBox = new javax.swing.JComboBox<>();
        headerjLabel = new javax.swing.JLabel();
        proceedjButton = new javax.swing.JButton();
        headerjLabel1 = new javax.swing.JLabel();
        addAreajComboBox = new javax.swing.JComboBox<>();
        addAreajButton = new javax.swing.JButton();
        manageSysAdminsjLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sysAdminsjTable = new javax.swing.JTable();
        countLablejLabel = new javax.swing.JLabel();
        countTotaljLabel = new javax.swing.JLabel();
        createjButton = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        updatejButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        headerjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headerjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerjLabel.setText("Choose a network from the below list TO PROCEED");

        proceedjButton.setText("Proceed >");
        proceedjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedjButtonActionPerformed(evt);
            }
        });

        headerjLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headerjLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerjLabel1.setText("Add Area? Choose from the list below");

        addAreajButton.setText("Add Area");
        addAreajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAreajButtonActionPerformed(evt);
            }
        });

        manageSysAdminsjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageSysAdminsjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageSysAdminsjLabel.setText("Manage System Administrators");

        sysAdminsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "S.No", "Name", "UserName", "Password", "Email", "Contact No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(sysAdminsjTable);
        if (sysAdminsjTable.getColumnModel().getColumnCount() > 0) {
            sysAdminsjTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        countLablejLabel.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        countLablejLabel.setText("Count :");

        countTotaljLabel.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        countTotaljLabel.setText("0");

        createjButton.setText("Create >");
        createjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createjButtonActionPerformed(evt);
            }
        });

        deletejButton.setText("Delete");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });

        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(areajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(proceedjButton)
                        .addGap(179, 179, 179)
                        .addComponent(addAreajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addAreajButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(headerjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(headerjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(manageSysAdminsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(countLablejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(countTotaljLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createjButton)
                    .addComponent(updatejButton)
                    .addComponent(deletejButton))
                .addGap(23, 23, 23))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {createjButton, deletejButton, updatejButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAreajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAreajButton)
                    .addComponent(proceedjButton))
                .addGap(68, 68, 68)
                .addComponent(manageSysAdminsjLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(createjButton)
                        .addGap(34, 34, 34)
                        .addComponent(updatejButton)
                        .addGap(41, 41, 41)
                        .addComponent(deletejButton)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countLablejLabel)
                    .addComponent(countTotaljLabel))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void proceedjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedjButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = areajComboBox.getSelectedIndex();
        System.out.println("Inside SystemAdminWorkAreaJPanel Panel -- proceedjButtonActionPerformed ");
        System.out.println("____________"+ecosystem.getAreaNetworks().get(selectedIndex)+"---------------");
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("adminMasterCityAreaPanel",new SystemAdminManageArea(userProcessContainer,ecosystem, ecosystem.getAreaNetworks().get(selectedIndex), userLogged));
        cardLayout.next(userProcessContainer);
        
    }//GEN-LAST:event_proceedjButtonActionPerformed

    private void addAreajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAreajButtonActionPerformed
        // TODO add your handling code here:
        
        for(AreaNetwork areaNetwork:ecosystem.getAreaNetworks()) {
            if(areaNetwork.getAreaName().name().equalsIgnoreCase((String) addAreajComboBox.getSelectedItem())){
                JOptionPane.showMessageDialog(this, "Area Already Exists. Please select another one");
                return;
            }
        }
        ecosystem.getAreaNetworks().add(new AreaNetwork(AreaName.valueOf((String) addAreajComboBox.getSelectedItem())));
        populateAreas();
    }//GEN-LAST:event_addAreajButtonActionPerformed

    private void createjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("CreateSysAdminPanel", new CreateNewSysAdminJPanel(userProcessContainer,ecosystem,userLogged));
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_createjButtonActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        // TODO add your handling code here:
        int selectedSysAdmin = sysAdminsjTable.getSelectedRow();
        if(selectedSysAdmin < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to Update");
            return;
        }
        
        DefaultTableModel sysAdminsModel = (DefaultTableModel) sysAdminsjTable.getModel();
        SysAdmin sysAdmin = (SysAdmin) sysAdminsModel.getValueAt(selectedSysAdmin, 1);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("UpdateSysAdminPanel", new UpdateSysAdminJPanel(userProcessContainer,ecosystem,sysAdmin,userLogged));
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_updatejButtonActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        // TODO add your handling code here:
        int selectedSysAdmin = sysAdminsjTable.getSelectedRow();
        if(selectedSysAdmin < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to Update");
            return;
        }
        
        DefaultTableModel sysAdminsModel = (DefaultTableModel) sysAdminsjTable.getModel();
        SysAdmin sysAdmin = (SysAdmin) sysAdminsModel.getValueAt(selectedSysAdmin, 1);
        if(ecosystem.getSysAdminDirectory().getSysAdmins().size()==1 || sysAdmin.getUserAccount().getUserName().equals(userLogged.getUserName())){
            JOptionPane.showMessageDialog(this, "Cannot delete Yourself");
            return;
        }
        ecosystem.getSysAdminDirectory().getSysAdmins().remove(sysAdmin);
        populateSysAdmins();
    }//GEN-LAST:event_deletejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAreajButton;
    private javax.swing.JComboBox<String> addAreajComboBox;
    private javax.swing.JComboBox<String> areajComboBox;
    private javax.swing.JLabel countLablejLabel;
    private javax.swing.JLabel countTotaljLabel;
    private javax.swing.JButton createjButton;
    private javax.swing.JButton deletejButton;
    private javax.swing.JLabel headerjLabel;
    private javax.swing.JLabel headerjLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageSysAdminsjLabel;
    private javax.swing.JButton proceedjButton;
    private javax.swing.JTable sysAdminsjTable;
    private javax.swing.JButton updatejButton;
    // End of variables declaration//GEN-END:variables
}
