/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import java.awt.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.*;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;

/**
 * @author braya
 */
public class UpdateUserJPanel extends javax.swing.JPanel {

  /**
   * Creates new form UpdateUserJPanel
   */
  JPanel cardSequenceJPanel;
  UserAccount userAccount;
  EcoSystem system;

  UpdateUserJPanel(JPanel cardSequenceJPanel, UserAccount userAccount, EcoSystem system) {
    initComponents();
    txtusername.setText(userAccount.getUsername());
    txtPassword.setText(userAccount.getPassword());
    txtname.setText(userAccount.getCustomer().getCustomerName());
    txtphonenumber.setText(userAccount.getCustomer().getPhoneNumber());
    txtrestaurantname.setText(userAccount.getCustomer().getRestaurant().getRestaurantName());
    this.cardSequenceJPanel = cardSequenceJPanel;
    this.userAccount = userAccount;
    this.system = system;


  }


  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        lblphonenumber = new javax.swing.JLabel();
        txtphonenumber = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblrestaurantname = new javax.swing.JLabel();
        txtrestaurantname = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 144, 37));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Customer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, -1));

        lblpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpassword.setText("Password");
        add(lblpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        lblusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblusername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusername.setText("UserName");
        add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        lblname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblname.setText("Name");
        add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));
        add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 160, -1));

        lblphonenumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblphonenumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblphonenumber.setText("Phone Number");
        add(lblphonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));
        add(txtphonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 170, -1));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 110, -1));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 130, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblrestaurantname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblrestaurantname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblrestaurantname.setText("Restaurant Name");
        add(lblrestaurantname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));
        add(txtrestaurantname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

  private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    // TODO add your handling code here:

    if (usernamePatternCorrect() == false) {
      lblusername.setForeground(Color.red);
      txtusername.setBorder(BorderFactory.createLineBorder(Color.RED));
      JOptionPane.showMessageDialog(null, "Username should be in the format of xx_xx@xx.xx");
      return;
    } else {
      lblusername.setForeground(Color.BLACK);
      txtusername.setBorder(BorderFactory.createLineBorder(Color.black));
    }
    if (passwordPatternCorrect() == false) {
      lblpassword.setForeground(Color.red);
      txtPassword.setBorder(BorderFactory.createLineBorder(Color.RED));
      JOptionPane.showMessageDialog(null, "Password should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
      return;
    } else {
      lblpassword.setForeground(Color.BLACK);
      txtPassword.setBorder(BorderFactory.createLineBorder(Color.black));
    }

    userAccount.setPassword(txtPassword.getText());
    userAccount.setUsername(txtusername.getText());
    userAccount.getCustomer().setCustomerName(txtname.getText());
    userAccount.getCustomer().setPhoneNumber(txtphonenumber.getText());
    Restaurant restaurant;
    if (system.getRestaurantDirectory().checkIfRestaurantnameIsUnique(txtrestaurantname.getText())){
        restaurant = new Restaurant(txtrestaurantname.getText());
        system.getRestaurantDirectory().addRestaurant(restaurant);
        
    }else{
        int index = system.getRestaurantDirectory().checkIfRestaurantExists(txtrestaurantname.getText());
        restaurant = system.getRestaurantDirectory().getRestaurantList().get(index);
    }
    userAccount.getCustomer().setRestaurant(restaurant);
    
    JOptionPane.showMessageDialog(this, "Updated Successfully");
    
//    txtPassword.setEnabled(false);
//    txtusername.setEnabled(false);
//    txtphonenumber.setEnabled(false);
//    btnSave.setEnabled(false);
  }//GEN-LAST:event_btnSaveActionPerformed

  private boolean usernamePatternCorrect() {
    Pattern p = Pattern.compile("^[a-zA-Z0-9]+_[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
    Matcher m = p.matcher(txtusername.getText());
    boolean b = m.matches();
    return b;
  }

  private boolean passwordPatternCorrect() {
    Pattern p1;
    p1 = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
    Matcher m1 = p1.matcher(txtPassword.getText());
    boolean b1 = m1.matches();
    return b1;
  }

  private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtPasswordActionPerformed

  private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    // TODO add your handling code here:
    
    cardSequenceJPanel.remove(this);
    CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
    layout.previous(cardSequenceJPanel);
  }//GEN-LAST:event_btnBackActionPerformed

  private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblphonenumber;
    private javax.swing.JLabel lblrestaurantname;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphonenumber;
    private javax.swing.JTextField txtrestaurantname;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
